### ISSUE TITLE
Update tests

### ISSUE THREAD

**Issue by LoicDelorme** [Slashgear/cloud-client-eval#2]
File: crud.specific.test.js

Problem: 204 should be removed

**it('should return empty object', done => {
            request.post('/user').send(simpleUser).end((err,res) => {
                request.delete(`/user/${res.body.id}`)
                    .expect(res => {
                        expect(res.body).toEqual({});
                    }).end(done);
            })
        });**

**Comment by Slashgear** [comment]
Je vais maintenir la 204 mais je vais enlever celui ou on test le body de la 204.

**Comment by Slashgear** [comment]
Fix with https://github.com/Slashgear/cloud-client-eval/releases/tag/v1.0.0
